### ISSUE TITLE
Suggestions N1

### ISSUE THREAD

**Issue by sergeitarasov** [diegosasso/ontophylo#1]
1. Amalgamate + Merge bins = the same function
2. Place do.call() inside respective functions
3. make_data_NHPP_KDE_Markov_kernel() + Add pseudo-data = same function
4.  What about a separate class for discretised trees (discr-multisimmap, and discr-simmap)?
5.  Merge Estimate Kernel Density Estimator and all following steps (requires some thinking).
6. Rename functions: KDE_unnorm_trunc_Markov
7. Differen funcitons for plot edge profiles 

---
1. Posteior paramater for lambda as argument.

**Comment by diegosasso** [comment]
1. Not necessary
2. Done. Modified: merge_tree_cat_list
3. Done. Modified: make_data_NHPP_KDE_Markov_kernel + PSD
4. Can be done later
5. Can be done later
6. Can be done later
7. Done. Modified: edgeplot
